image: php:7.2-fpm

before_script:
  # - apt-get update
  # - apt-get install curl
  - curl -s https://getcomposer.org/installer | php
  - mv composer.phar /usr/local/bin/composer
  - composer install 

stages:
  - lint
  - test

linter:
  stage: lint
  script: 
    - php -l .
    - ./vendor/bin/phpcs  --standard=PSR2 src

# linter:
#   stage: test
#   script: 
#     - php -l .
#     - ./vendor/bin/phpcs  --standard=PSR2 src
