image: ros65536/php-shlink-ci

services:
  - docker:dind

variables:
  # https://gist.github.com/douglasmiranda/9b899c748e915173c8f19d948bbdc69c#docker-in-docker-doesnt-work-in-gitlab-runner-exec-docker
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay

# before_script:
#   - composer install

stages:
  - lint
  - test

# linter:
#   stage: lint
#   script: 
#     - php -l .
#     - ./vendor/bin/phpcs  --standard=PSR2 src

tests:
  services:
    - name: "shlinkio/shlink:1.20.2"
      alias: shlink
  stage: test
  script: 
    - docker image ls
    # - php -l .
    # - SHLINK_HOST=localhost:8080 SHLINK_API_KEY=$(./generate-api-key.sh) ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests